### ISSUE TITLE
need support for 10 gig interfaces

### ISSUE THREAD

**Issue by craigers521** [CiscoTestAutomation/genielibs#1]
Specifically was trying to use the show_ospf library and keep choking on trying to load a TenGigabitEthernet interface.  I changed the regex in one place but then it broke in another.  Please add support for 10gig.

**Comment by jeaubin** [comment]
On which os are you looking, and do you have sample device output?

**Comment by craigers521** [comment]
Switch is ios-xe, running script of mac, but would like to get working on redhat.  Here is where the script bombs if that is what you are asking: 

`Traceback (most recent call last):
  File "route-tracker.py", line 67, in <module>
    main()
  File "route-tracker.py", line 54, in main
    ospf = tasks.learn('ospf', uut)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipyats/tasks/__init__.py", line 100, in learn
    feature_details.learn()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/genie/libs/ops/ospf/iosxe/ospf.py", line 1006, in learn
    self.make()
  File "src/genie/ops/base/base.py", line 95, in genie.ops.base.base.Base.make
  File "src/genie/ops/base/maker.py", line 240, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 321, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 281, in genie.metaparser._metaparser.MetaParser.parse
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_ospf.py", line 4291, in cli
    if interface not in ret_dict['vrf'][vrf]['address_family'][af]\
UnboundLocalError: local variable 'interface' referenced before assignment`

**Comment by craigers521** [comment]
well that output i posted shows it bombing on line 4291.  Looking at the show_ospf.py code that variable is defined on line 4229.  I fixed the regex there but then immediately ran into another failure... seemed like i opened a can of worms so was hoping you guys could just "fix" TenGig across the board.

**Comment by jeaubin** [comment]
We'll fix it.  Gathering a device with TenGig and fixing the parsers.

If you want you can also email us your device show commands at pyats-support-ext@cisco.com  and we can make sure it works on your device too.

**Comment by craigers521** [comment]
Thanks for the quick turnaround on that.  That regex change got me past that error but unfortunately I ended up with another similar error where it looks like a variable is being referenced before instantiated: 

> File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_ospf.py", line 1410, in cli
    if intf_type == 'interfaces':
UnboundLocalError: local variable 'intf_type' referenced before assignment

I can include my testbed yaml if that's helpful.  Thanks.

**Comment by karmoham** [comment]
Hi Craig,

We fixed the issue and released genie.libs.parser v3.1.10.

Please do "pip install --upgrade genie.libs.parser" to get the latest package.

Thanks,
Karim
