### ISSUE TITLE
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys

### ISSUE THREAD

**Issue by sshekha3** [CiscoTestAutomation/genielibs#101]
Hi Team, 
I am a beginner in writing genie parser, trying to write a parser for "show hardware led" for IOS-XE.

I am getting this error, crosschecked my schema class and it looks good to me. I am confused like what is triggering this error message.  

Traceback (most recent call last):
  File "tester.py", line 10, in <module>
    output = device.parse("show hardware led")
  File "/nobackup/sshekha3/pyats-training/lib/python3.8/site-packages/genie/conf/base/device.py", line 527, in parse
    return self._get_parser_output(kwargs, parsers[0], parsers[1], 
  File "/nobackup/sshekha3/pyats-training/lib/python3.8/site-packages/genie/conf/base/device.py", line 561, in _get_parser_output
    out = parser(getattr(self, alias), context=context).parse(**copy)
  File "/nobackup/sshekha3/pyats-training/lib/python3.8/site-packages/genie/metaparser/_metaparser.py", line 292, in parse
    output = Schema(self.schema).validate(
  File "/nobackup/sshekha3/pyats-training/lib/python3.8/site-packages/genie/metaparser/util/schemaengine.py", line 415, in validate
    raise SchemaMissingKeyError(missed_keys_path,
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['switch', 1, 'intf_led_status'], ['switch', 1, 'intf_led_poe'], ['switch', 1, 'intf_led_duplex'], ['switch', 1, 'intf_led_speed'], ['switch', 1, 'intf_led_stack']]

Thanks 
Shashi Shekhar

**Comment by omehrabi** [comment]
my guess here is that the pattern is matched from the device output is not matching the output schema. I encourage you to take pyats certification to get more familiar with writing parsers for pyats.

**Comment by sshekha3** [comment]
Sure

Actually there was one error in class ShowHardwareLed while matching patterns.

Thanks omehrabi

**Comment by sshekha3** [comment]
hey omehrabi,

one more question I need to ask, like If someone has already written parser for "show hardware led" but it's from different product line which has completely different output compared to my output.
What should I do in this case? 

Thanks

**Comment by omehrabi** [comment]
you could add one for that specific os or platform.
