### ISSUE TITLE
genie.metaparser.util.exceptions.SchemaMissingKeyError: Show Command: show ip ospf interface  Missing keys: 

### ISSUE THREAD

**Issue by cwolfe1** [CiscoTestAutomation/genielibs#107]
Issue while parsing: <class 'genie.libs.parser.ios.show_ospf.ShowIpOspfInterface'>

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/home/cwolfe1/.local/lib/python3.8/site-packages/genie/libs/ops/ospf/iosxe/ospf.py", line 1017, in learn
    self.make(final_call=True)
  File "/home/cwolfe1/.local/lib/python3.8/site-packages/genie/ops/base/base.py", line 103, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 342, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 419, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Show Command: show ip ospf interface 
Missing keys: 
[
['vrf', 'default', 'address_family', 'ipv4', 'instance', '111', 'areas', '0.0.0.0', 'interfaces', 'GigabitEthernet1/1', 'authentication', 'auth_trailer_key', 'crypto_algorithm'], 
['vrf', 'default', 'address_family', 'ipv4', 'instance', '111', 'areas', '0.0.0.0', 'interfaces', 'Vlan110', 'authentication', 'auth_trailer_key', 'crypto_algorithm'], 
['vrf', 'default', 'address_family', 'ipv4', 'instance', '111', 'areas', '0.0.0.0', 'interfaces', 'Vlan114', 'authentication', 'auth_trailer_key', 'crypto_algorithm'], 
['vrf', 'default', 'address_family', 'ipv4', 'instance', '111', 'areas', '0.0.0.0', 'interfaces', 'Vlan116', 'authentication', 'auth_trailer_key', 'crypto_algorithm']
]

**Comment by Taarini** [comment]
Can you please share the device output for the command. Also please share the os and platform used

**Comment by cwolfe1** [comment]
sorry not able to share, OS is RHEL7, platform is cisco WS-C6509-E

**Comment by Taarini** [comment]
If you can't share the actual device output, you can modify the values which are confidential. Without device output it would be difficult to debug

**Comment by Taarini** [comment]
The issue will be closed if there is no update for 30 days

**Comment by Taarini** [comment]
No update hence closing
