### ISSUE TITLE
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['sslproxy_statistics', 'connection_statistics', 'tunneled_non-proxied_connections']]

### ISSUE THREAD

**Issue by ashirpra** [CiscoTestAutomation/genielibs#109]
I  was trying to parse some parameters from "show sslproxy statistics". 
but i am getting
"genie.metaparser.util.exceptions.SchemaMissingKeyError",

Code for the above is :

                execute_num = parser_handle.parse("show sslproxy statistics")
                tunneled_proxied = execute_num['sslproxy_statistics']['connection_statistics']['tunneled_proxied_connections']
                log.info(tunneled_proxied)

Error Message : 
2022-08-25T14:02:52: %AETEST-ERROR: Caught an exception while executing section sn_status_check:
2022-08-25T14:02:52: %AETEST-ERROR: Traceback (most recent call last):
2022-08-25T14:02:52: %AETEST-ERROR:   File "/ws/ashirpra-bgl/pyats/projects/pyats_sdwan/scripts/appqoe-ashirpra/upgrade.py", line 2256, in sn_status_check
2022-08-25T14:02:52: %AETEST-ERROR:     execute_num = parser_handle.parse("show sslproxy statistics")
2022-08-25T14:02:52: %AETEST-ERROR:   File "/ws/ashirpra-bgl/pyats/lib/python3.8/site-packages/genie/conf/base/device.py", line 528, in parse
2022-08-25T14:02:52: %AETEST-ERROR:     return self._get_parser_output(kwargs, parsers[0], parsers[1],
2022-08-25T14:02:52: %AETEST-ERROR:   File "/ws/ashirpra-bgl/pyats/lib/python3.8/site-packages/genie/conf/base/device.py", line 565, in _get_parser_output
2022-08-25T14:02:52: %AETEST-ERROR:     out = parser_instance.parse(**copy)
2022-08-25T14:02:52: %AETEST-ERROR:   File "/ws/ashirpra-bgl/pyats/lib/python3.8/site-packages/genie/metaparser/_metaparser.py", line 322, in parse
2022-08-25T14:02:52: %AETEST-ERROR:     output = Schema(self.schema).validate(
2022-08-25T14:02:52: %AETEST-ERROR:   File "/ws/ashirpra-bgl/pyats/lib/python3.8/site-packages/genie/metaparser/util/schemaengine.py", line 419, in validate
2022-08-25T14:02:52: %AETEST-ERROR:     raise SchemaMissingKeyError(missed_keys_path,
2022-08-25T14:02:52: %AETEST-ERROR: genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['sslproxy_statistics', 'connection_statistics', 'tunneled_non-proxied_connections']]

**Comment by Taarini** [comment]
Hi 

Can you please share the device output of the show command which you are facing the issue. Also please share the OS and platform used for the above

**Comment by ashirpra** [comment]
Hi Taarini,
Thanks for the Reply.

Device details:
os: iosxe
        alias: Isn4451 
        series: sdwan
        type: iosxe
        platform: sdwan


Here is the device output :
Isn4451#show sslproxy statistics
==========================================================
              SSL Proxy Statistics
==========================================================
Connection Statistics:
 Total Connections                  : 0
 Proxied Connections                : 0
 Non-proxied Connections            : 0
 Clear Connections                  : 0
 Active Proxied Connections         : 0
 Active Non-proxied Connections     : 0
 Active Clear Connections           : 0
 Max Conc Proxied Connections       : 0
 Max Conc Non-proxied Connections   : 0
 Max Conc Clear Connections         : 0
 Tunneled Proxied Connections       : 0
 Tunneled Non-proxied Connections   : 0
 Active Tunneled Proxied Flows      : 0
 Active Tunneled Non-proxied Flows  : 0
 Max Conc Tunneled Proxied Flows    : 0
 Max Conc Tunneled Non-proxied Flows: 0
 SSL Encrypted marked Non SSL Flows : 0
 Total Closed Connections           : 0

Non-proxied Connection Reasons:
 Unsupported Cipher                 : 0
 Unsupported SSL Version            : 0
 Non SSL Traffic                    : 0
 Memory Allocation Failure          : 0
 Memory Access Failure              : 0
 Handshake Unsupported              : 0
 SSL Parse Failure                  : 0
 SSL Error                          : 0
 Unexpected Packet                  : 0
 ISM State Error                    : 0
 Exception                          : 0
 Endpoint Alert                     : 0
 FIN/RST Received during handshake  : 0
 Pushdown by SC                     : 0
 ISM Flow Create Failure            : 0
 Pushdown Default                   : 0

Dropped Connection Reasons:
 Unsupported SSL Version            : 0
 Unsupported Cipher                 : 0
 Untrusted Certificate              : 0
 Unable to get Proxy certificate    : 0
 Expired Certificate                : 0
 OCSP Cert Verification Failure     : 0
 Handshake Unsupported              : 0
 Endpoint Alert                     : 0
 FIN/RST Received during handshake  : 0
 Read in Invalid State              : 0
 Invalid FSM Event Received         : 0
 Invalid Msg Type Rcvd from ISM/DE  : 0
 Event Received in Wrong State      : 0
 ISM Key Packet Send Fail           : 0
 ISM Flow Create Failure            : 0
 Failed to Load Key in DE           : 0
 Invalid Peer Segment               : 0
 Fail to get Orig CH during Pushdown: 0
 Decrypt/Encrypt Failure            : 0
 RST Rcvd during PS/PC key pending  : 0
 No SSL Record in Flow Segment      : 0
 Memory Allocation Failure          : 0
 Memory Access Failure              : 0
 Abort on SSL Parse Failure         : 0
 Invalid SSL Record Header          : 0
 Unable to send HS message to ISM   : 0
 Fail to get Memory from Pool in ISM: 0

Alert Generated:
 C2S                                : 0
 S2C                                : 0

Alert Received:
 C2S                                : 0
 S2C                                : 0

Connection Closure Statistics:
C2S
 FIN Received at PS                 : 0
 FIN Rec after SSL Handshake at PS  : 0
 FIN Rec during SSL Handshake at PS : 0
 FIN Rec for Non-SSL Conn at PS     : 0
 FIN Sent to SC from PS             : 0
 FIN Received at PC from SC         : 0
 FIN Sent to Server                 : 0
 RST Generated by PS                : 0
 RST Received at PS                 : 0
 RST Sent to SC from PS             : 0
 RST Received at PC from SC         : 0
 RST Sent to Server                 : 0
 Close Notify Received at PS        : 0
 Close Notify FIN Sent to SC from PS: 0
 Close Notify FIN Rec at PC from SC : 0
 Close Notify Sent to Server        : 0
S2C
 FIN Received at PC                 : 0
 FIN Rec after SSL Handshake at PC  : 0
 FIN Rec during SSL Handshake at PC : 0
 FIN Rec for Non-SSL Conn at PC     : 0
 FIN Sent to SC from PC             : 0
 FIN Received at PS from SC         : 0
 FIN Sent to Client                 : 0
 RST Generated by PC                : 0
 RST Received at PC                 : 0
 RST Sent to SC from PC             : 0
 RST Received at PS from SC         : 0
 RST Sent to Client                 : 0
 Close Notify Received at PC        : 0
 Close Notify FIN Sent to SC from PC: 0
 Close Notify FIN Rec at PS from SC : 0
 Close Notify Sent to Client        : 0

Proxy Server:
 LWSSL Flow Create                  : 0
 LWSSL Flow Delete                  : 0
 LFS mem alloc failure              : 0
 FIN Generated by SC                : 0
 RST Generated by SC                : 0
 Close Notify Sent                  : 0

Proxy Client:
 LWSSL Flow Create                  : 0
 LWSSL Flow Delete                  : 0
 LFS mem alloc failure              : 0
 FIN Generated by SC                : 0
 RST Generated by SC                : 0
 Close Notify Sent                  : 0

ISM:
 ISM Flow Create                    : 0
 ISM Flow Delete                    : 0
 ISM FIFO Enqueue Failed            : 0
 ISM Sem Post Failed                : 0
 LWSSL Failed to Send Msg           : 0
 LWSSL Mem alloc failed for ISM Msg : 0

Resource Manager:
 Session Alloc Success              : 0
 Session Alloc Failures             : 0
 Session Free Success               : 0
 Session Free Failures              : 0

OCSP Statistics:
APP Statistics
 OCSP Requests                      : 0
 OCSP Responses                     : 0
 OCSP Timeouts                      : 0
 OCSP Failures                      : 0
 OCSP Good responses                : 0
 OCSP Revoked responses             : 0
 OCSP Unknown responses             : 0
 OCSP Internal Errors               : 0
Client Statistics
 OCSP Requests                      : 0
 OCSP Responses                     : 0
 OCSP Timeouts                      : 0
 OCSP Failures                      : 0
 OCSP Good responses                : 0
 OCSP Revoked responses             : 0
 OCSP Unknown responses             : 0
 OCSP Internal Errors               : 0

OCSP Stapling:
 OCSP Stapling Requests             : 0
 OCSP Stapling Responses            : 0
 OCSP Stapling Valid Responses      : 0
 OCSP Stapling Revoked Responses    : 0
 OCSP Stapling Unknown Responses    : 0
 OCSP Response Validation Failure   : 0

SSL Statistics:
Flow Requested SSL/TLS version:
 SSL V2 Flows                       : 0
 SSL V3 Flows                       : 0
 TLS 1.0 Flows                      : 0
 TLS 1.1 Flows                      : 0
 TLS 1.2 Flows                      : 0
 TLS 1.3 Flows                      : 0
Flow Selected SSL/TLS version:
 TLS 1.0 Flows                      : 0
 TLS 1.1 Flows                      : 0
 TLS 1.2 Flows                      : 0
Client Hello Extensions:
 Pushdown                           : 0
 Bypass                             : 0
 Strip                              : 0
 Process                            : 0
SSL Handshake Statistics:
 SSL Handshakes Started             : 0
 SSL Handshakes Completed           : 0
 Full SSL Handshakes                : 0
 SSL Renegotiation                  : 0
 SSL Resumption                     : 0
 SSL Resumption session ID          : 0
 SSL Resumption session tkt         : 0
 SSL fallback to full hs            : 0
 SSL failed renego                  : 0
 SSL server cert validation reqs    : 0
 SSL server cert validation success : 0
 Server cert verify failed expired  : 0
 Server cert verify failed untrusted: 0
 SSL client cert validation reqs    : 0
 SSL client cert validation success : 0
 Client cert verify failed expired  : 0
 Client cert verify failed untrusted: 0
 Revocation Check Requests          : 0
 Revocation Check Good Response     : 0
Policy Statistics:
Drop
 expired-certificate                : 0
 failure-mode                       : 0
 unknown-status                     : 0
 unsupported-cipher-suites          : 0
 unsupported-protocol-versions      : 0
 untrusted-certificate              : 0
Decrypt
 expired-certificate                : 0
 failure-mode                       : 0
 unknown-status                     : 0
 untrusted-certificate              : 0
No Decrypt
 unsupported-cipher-suites          : 0
 unsupported-protocol-versions      : 0

Packet Counters:
Proxy Server
 From Client                        : 0
 To SC                              : 0
 From SC                            : 0
 To Client                          : 0
Proxy Client
 From Server                        : 0
 To SC                              : 0
 From SC                            : 0
 To Server                          : 0
Clear Packets:
Proxy Server
 From Client                        : 0
 To SC                              : 0
 From SC                            : 0
 To Client                          : 0
Proxy Client
 From Server                        : 0
 To SC                              : 0
 From SC                            : 0
 To Server                          : 0
Dropped Packets:
 C2S WCAPI DENY packet              : 0
 S2C WCAPI DENY packet              : 0

Here is the code for the same :
               show_sslproxy_statistics = parser_handle.parse("show sslproxy statistics")
                sslproxy_actv_prxy_conn = show_sslproxy_statistics['sslproxy_statistics']['connection_statistics']['active_proxied_connections']
                print("Output is this : ", sslproxy_actv_prxy_conn)

**Comment by Taarini** [comment]
Hi 

The reason for the above error is because the below mentioned keys are missing in the schema definition of connection_statistics.

- 'tunneled_non_proxied_connections',
- 'tunneled_proxied_connections', 
- 'active_tunneled_proxied_flows', 
- 'max_conc_tunneled_non_proxied_flows', 
- 'active_tunneled_non_proxied_flows',
- 'ssl_encrypted_marked_non_ssl_flows', 
- 'max_conc_tunneled_proxied_flows'

Sharing the schema link for you to cross-check your output with the existing schema keys, https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_sslproxy.py#L127

So you can update the parser with the missing keys and fix them.

pyATS parser is community driven.

Please consider contributing to pyATS genie parser library.

Below is a link with instructions on how to write a parser:
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

If you need any help, please let me know by creating a pull request for the above issue

**Comment by Taarini** [comment]
The issue will be closed after 3 business days

**Comment by Taarini** [comment]
Closing this issue since there is no reply from user
