### ISSUE TITLE
Learn acl model parser exception on Cisco NXOS in genie/libs/parser/nxos/show_acl.py: UnboundLocalError 'acl_dict' 

### ISSUE THREAD

**Issue by Sulray** [CiscoTestAutomation/genielibs#154]
When doing the CLI command genie learn acl--testbed-file /folder/testbed.yaml --devices {my_device_hostname} -v, I have an exception traceback:

> Issue while building the feature
> 
> Traceback (most recent call last):
>   File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
>   File "/folder/.venv/lib/python3.8/site-packages/genie/libs/ops/acl/nxos/acl.py", line 239, in learn
>     self.make(final_call=True)
>   File "/folder/.venv/lib/python3.8/site-packages/genie/ops/base/base.py", line 103, in make
>     self.maker.make(*args, **kwargs)
>   File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
>   File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
>   File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
>   File "/folder/.venv/lib/python3.8/site-packages/genie/libs/parser/nxos/show_acl.py", line 426, in cli
>     acl_dict.update({'total_aces_configured': int(group['total_aces_configured'])}),
> UnboundLocalError: local variable 'acl_dict' referenced before assignment

The error appears in the following block of code https://github.com/CiscoTestAutomation/genieparser/blob/882c298551531705697c097fa054f6573fa2c2de/src/genie/libs/parser/nxos/show_acl.py#L426 : 
```
            if m:
                group = m.groupdict()
                total_configured=int( group['total_aces_configured'] )
                acl_dict.update({'total_aces_configured': int(group['total_aces_configured'])}),
                continue
```
And since acl_dict is defined in the following block:
```
            # IPV4 ACL acl_name
            # IPV4 ACL sl_def_acl
            m = p1.match(line) 
            if m:
                group = m.groupdict()
                acl_dict = result_dict.setdefault('acl',{}).setdefault(group['name'],{})
                acl_name=group['name']
                if group['status']:
                    acl_dict.update({'Statistics': group['status']})      
                continue
```
It could mean that regex p1 isn't matched.

The device is a Cisco NXOS:

Software
BIOS: version 2.19.0
kickstart: version 7.3(3)D1(1)
system: version 7.3(3)D1(1)

Hardware
cisco Nexus7000 C7018 (18 Slot) Chassis ("Supervisor Module-2")

**Comment by Harishv01** [comment]
Hello Sulray,

Currently, I am working on it, kindly give me some time to debug it.

Thank you.

**Comment by Harishv01** [comment]
Hi,

Can you share the raw output?

**Comment by Sulray** [comment]
Hi Harishv,

Do you mean the raw output of the learn command directly or the output of the command which led to an error in the learn ?

**Comment by Harishv01** [comment]
Hi Sulray,
Please provide both the output of the command that resulted in an error and the command as well.

**Comment by Harishv01** [comment]
Hi Sulray,
Please provide both the output of the command that resulted in an error and the command as well.

**Comment by Harishv01** [comment]
Hi Sulray,
Please provide both the output of the command that resulted in an error and the command as well.

**Comment by Sulray** [comment]
### The command was :
genie learn acl --testbed-file ./testbed.yaml --devices a1aaabb1 -v

### The output in the terminal at the end was :
```
+==============================================================================+
| Genie Learn Summary for device a1aaabb1                                      |
+==============================================================================+
|  Connected to a1aaabb1                                                       |
|  -   Log: ./connection_a1aaabb1.txt                                          |
|------------------------------------------------------------------------------|
|  Could not learn feature 'acl'                                               |
|  -  Exception:      ./acl_nxos_a1aaabb1_exception.txt                        |
|  -  Ops structure:  ./acl_nxos_a1aaabb1_ops.txt                              |
|  -  Device Console: ./acl_nxos_a1aaabb1_console.txt                          |
|==============================================================================|

```

### In ./acl_nxos_a1aaabb1_exception.txt:

Issue while building the feature

```
Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/home/user/project/.venv/lib/python3.8/site-packages/genie/libs/ops/acl/nxos/acl.py", line 239, in learn
    self.make(final_call=True)
  File "/home/user/project/.venv/lib/python3.8/site-packages/genie/ops/base/base.py", line 103, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/user/project/.venv/lib/python3.8/site-packages/genie/libs/parser/nxos/show_acl.py", line 426, in cli
    acl_dict.update({'total_aces_configured': int(group['total_aces_configured'])}),
UnboundLocalError: local variable 'acl_dict' referenced before assignment
```

### In ./acl_nxos_a1aaabb1_ops.txt:

```
{
  "_exclude": [],
  "attributes": null,
  "commands": null,
  "connections": null,
  "context_manager": {},
  "raw_data": false
}
```

### In ./fdb_nxos_a1aaabb1_console.txt (replaced IPs with x.x.x.x/x but they are all correct IPs):

```
+++ a1aaabb1 with via 'cli': executing command 'show access-lists' +++
show access-lists

IP access list 199
        10 remark COMMENT01
        20 permit ip x.x.x.x/x any 
        30 remark COMMENT02
        40 permit ip x.x.x.x/x any 
        50 remark COMMENT03
        60 permit ip x.x.x.x/x any 
        70 remark COMMENT04
        80 permit ip x.x.x.x/x any 
        90 remark COMMENT05
        100 permit ip x.x.x.x/x any 
IP access list 98
        10 remark COMMENT06
        20 permit ip x.x.x.x/x any 
        30 permit ip x.x.x.x/x any 
        40 permit ip x.x.x.x/x any 
        50 permit ip x.x.x.x/x any 
        60 permit ip x.x.x.x/x any 
        70 permit ip x.x.x.x/x any 
        71 permit ip x.x.x.x/x any 
        80 remark COMMENT01
        90 permit ip x.x.x.x/x any 
        100 permit ip x.x.x.x/x any 
IP access list 99
        10 remark PAS - COMMENT07
        20 permit ip x.x.x.x/x any 
        30 permit ip x.x.x.x/x any 
IP access list COMMENT08
        10 permit ip any x.x.x.x/x

a1aaabb1# 
+++ a1aaabb1 with via 'cli': executing command 'show access-lists summary' +++
show access-lists summary


IP access list 199
        Total ACEs Configured: 5
        Configured on interfaces:
                VTY         - ingress
        Active on interfaces:
                VTY         - ingress
IP access list 98
        Total ACEs Configured: 9
        Configured on interfaces:
        Active on interfaces:
IP access list 99
        Total ACEs Configured: 2
        Configured on interfaces:
        Active on interfaces:
IP access list COMMENT09
        Total ACEs Configured: 1
        Configured on interfaces:
                Ethernetxx/x.xxx - egress (Router ACL)
        Active on interfaces:
                Ethernetxx/x.xxx - egress (Router ACL)
IP access list COMMENT10
        Total ACEs Configured: 1
        Configured on interfaces:
        Active on interfaces:
IPv6 access list COMMENT11
        Total ACEs Configured: 1
        Configured on interfaces:
        Active on interfaces:

a1aaabb1# 
```

**Comment by Harishv01** [comment]
okay,I will check and get  back asap

**Comment by Harishv01** [comment]
Hi Sulray,

I have raised a pull request for this. Once it is merged, I will let you know.

Thank you!!

**Comment by Harishv01** [comment]
Hi,

I have merged the pull request, and you will see the fix in the next version, i.e., 24.3. Therefore, I am closing this ticket

Thank you!
