### ISSUE TITLE
IOSXR learn LLDP key issue

### ISSUE THREAD

**Issue by laroccacristian** [CiscoTestAutomation/genielibs#23]
Hi there!

I'm receiving a key error when I try to learn LLDP on a NCS5501. I'm running genie.libs.parser 20.7.1b1

RP/0/RP0/CPU0:bne-lab-ncs-1#
Error deteced <class 'genie.metaparser.util.exceptions.SchemaMissingKeyError'>:Missing keys: [['interfaces', 'GigabitEthernet0/0/0/1', 'port_id', 'Cc4e.2495.5a00', 'neighbors', 'bne-lab-mlx-1', 'system_description'], ['interfaces', 'TenGigE0/0/0/10', 'port_id', '40a6.b71d.b64b', 'neighbors'], ['interfaces', 'TenGigE0/0/0/13', 'port_id', '6cab.0573.2166', 'neighbors'], ['interfaces', 'TenGigE0/0/0/14', 'port_id', '40a6.b71d.b69a', 'neighbors'], ['interfaces', 'TenGigE0/0/0/15', 'port_id', '40a6.b71d.b69b', 'neighbors'], ['interfaces', 'TenGigE0/0/0/16', 'port_id', '40a6.b71d.b6db', 'neighbors']]
Traceback (most recent call last):
  File "hello_genie.py", line 61, in main
    lldp = device.learn('lldp')
  File "src/genie/conf/base/device.py", line 627, in genie.conf.base.device.Device.learn
  File "/Users/cristian.la.rocca/Documents/Development/NetworkOperations/genie/lib/python3.8/site-packages/genie/libs/ops/lldp/iosxr/lldp.py", line 137, in learn
    self.make(final_call=True)
  File "/Users/cristian.la.rocca/Documents/Development/NetworkOperations/genie/lib/python3.8/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['interfaces', 'GigabitEthernet0/0/0/1', 'port_id', 'Cc4e.2495.5a00', 'neighbors', 'bne-lab-mlx-1', 'system_description'], ['interfaces', 'TenGigE0/0/0/10', 'port_id', '40a6.b71d.b64b', 'neighbors'], ['interfaces', 'TenGigE0/0/0/13', 'port_id', '6cab.0573.2166', 'neighbors'], ['interfaces', 'TenGigE0/0/0/14', 'port_id', '40a6.b71d.b69a', 'neighbors'], ['interfaces', 'TenGigE0/0/0/15', 'port_id', '40a6.b71d.b69b', 'neighbors'], ['interfaces', 'TenGigE0/0/0/16', 'port_id', '40a6.b71d.b6db', 'neighbors']]

Regards!

**Comment by LenzDong** [comment]
Hi,

The fix is released in genie.libs.parser v20.7.1b2 .
Please update the parser packages and try:
“pip install --upgrade --pre genie.libs.parser”

Thanks
