### ISSUE TITLE
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['protocols', 'ospf', 'vrf', 'default', 'address_family', 'ipv4', 'instance', '32', 'incoming_filter_list']]

### ISSUE THREAD

**Issue by doug1as** [CiscoTestAutomation/genielibs#35]
I'm trying to learn ospf feature but in some routers i had this error:

Issue while parsing: <class 'genie.libs.parser.iosxe.show_protocols.ShowIpProtocols'>

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/home/douglas.rodrigues/.local/lib/python3.8/site-packages/genie/libs/ops/ospf/iosxe/ospf.py", line 1017, in learn
    self.make(final_call=True)
  File "/home/douglas.rodrigues/.local/lib/python3.8/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['protocols', 'ospf', 'vrf', 'default', 'address_family', 'ipv4', 'instance', '32', 'incoming_filter_list']]

in the line "Issue while parsing", it's referencing iosxe, but i has this same issue on ios and iosxe routers (some routers, not all)

**Comment by badalsoyantar** [comment]
Hi Can you share device output to pyats-support-ext@cisco.com it seems parser issue.

**Comment by doug1as** [comment]
Hi @badalsoyantar, what kind of output you need ? 
All files generated of "genie parse" command ?

**Comment by doug1as** [comment]
@badalsoyantar, i sended now all files generated by "genie learn" command for pyats-support-ext@cisco.com ...

Regards !

**Comment by badalsoyantar** [comment]
Hello @doug1as It was optional key issue and is fixed. I will ping you once beta package is released for you.
