### ISSUE TITLE
SchemaMissingKeyError while trying to learn ISIS information 

### ISSUE THREAD

**Issue by Tristou27** [CiscoTestAutomation/genielibs#36]
Hello there,

# Issue
I'm pretty new using pyATS / Genie so I'm not really sure that it's a bug or if I am missing something.
Trying to learn ISIS state on a ASR1K w/ IOS-XE, and here's what I've seen:

Could you please have a look at it ? 
Thanks.

Tristan
```
Traceback (most recent call last):
  File "script.py", line 14, in <module>
    isis = testbed.devices[dev].learn('isis')
  File "src/genie/conf/base/device.py", line 626, in genie.conf.base.device.Device.learn
  File "/home/AD.TB.PAR.EQUANT.COM/ttr/PyAutomationTests/projects/pyats/pyats_venv/lib/python3.6/site-packages/genie/libs/ops/isis/iosxe/isis.py", line 446, in learn
    self.make()
  File "/home/AD.TB.PAR.EQUANT.COM/ttr/PyAutomationTests/projects/pyats/pyats_venv/lib/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['tag', 'null', 'IS-IS', 'dr_election', 'level-1'], ['tag', 'null', 'IS-IS', 'spf_calculation', 'level-1'], ['tag', 'null', 'IS-IS', 'partial_route_calculation', 'level-1']]
```

Here's the (pretty basic) code leading to this error : 
```
from genie.testbed import load

testbed = load('testbed.yaml')

for dev in testbed.devices.keys():
    testbed.devices[dev].connect(via='cli')
    isis = testbed.devices[dev].learn('isis')
    pprint.pprint(isis)
```

### Environment
Python 3.6.9 with PyATS & Genie 20.10
ASR1009-X w/ IOS-XE 16.6.3

**Comment by Tristou27** [comment]
Hello @xiaoxinz-cisco 

Thanks for this prompt answer and advices :slightly_smiling_face:
Indeed, it was concerning genieparser and not genielibs, my apologies.

I've submitted a pull request #340 [here on genielibs](https://github.com/CiscoTestAutomation/genieparser/pull/340)

I let you decide if you want to close this issue or not. 

Thanks

**Comment by xiaoxinz-cisco** [comment]
Hello @Tristou27 ,

Thanks for your contribution. We will review your PR in short. I'll close the issue once your PR is merged.

Thanks
