### ISSUE TITLE
Parse "show inventory" issue on 7600 platform

### ISSUE THREAD

**Issue by OmarCCIE** [CiscoTestAutomation/genielibs#50]
Hello, 

I am building a basic script to retrieve the inventory from a customer installed based, however there is an exception when I run the command towards a 7600 router having the following error: 

Issue with the parser show inventory

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 522, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 549, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/.local/share/virtualenvs/pyats-bfefOSfd/lib/python3.6/site-packages/genie/libs/parser/ios/show_platform.py", line 303, in cli
    subslot_dict = slot_dict\
UnboundLocalError: local variable 'slot_dict' referenced before assignment

I am attaching the console output for your reference.

Files already sent to pyats-support-ext@cisco.com

**Comment by OmarCCIE** [comment]
Adding the following custom header to the devices on the testbed file fixed the connectivity: 

    custom:
      abstraction:
        order:
        - os
        - platform
