### ISSUE TITLE
Verify Boot Variable - KeyError 'com' in Robot

### ISSUE THREAD

**Issue by oianson** [CiscoTestAutomation/genielibs#53]
When I try and use the following robot API keyword
```
Verify Boot Variable   device=D1-INETIU-C9800   boot_images=packages.conf
```
I get the following traceback:

```
KeyError: 'com'

Traceback (most recent call last):
  File "/home/cisco/cxta/workspace/genielibs/pkgs/robot-pkg/src/genie/libs/robot/GenieRobotApis.py", line 35, in run_keyword
    return self.api.get_api(name.strip().replace(' ', '_'), device_handler)(device_handler, *args, **kwargs)
  File "/home/cisco/cxta/workspace/genielibs/pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/platform/verify.py", line 148, in verify_boot_variable
    if boot_images == device.api.get_boot_variables(device=device, boot_var='next'):
  File "src/genie/conf/base/api.py", line 99, in genie.conf.base.api.API.__getattr__.wrapper_match
  File "src/genie/conf/base/api.py", line 150, in genie.conf.base.api.API.get_api
```

I am able to use the following API without issue:
```
Get Boot Variables  device=${DUT}  boot_var=current

**Comment by LukasMcClelland** [comment]
Hi @oianson , thank you for bringing this to our attention. I'll be looking into this issue

**Comment by LukasMcClelland** [comment]
Currently, the only OS that supports the `verify_boot_variable` API is IOSXE ([link here](https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/apis/verify_boot_variable)). 

While the `get_boot_variables` API ([link here](https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/apis/get_boot_variables)) is supported by IOSXE, cat9500, and cat9k.

If you're you using an OS other than iosxe, then the Verify Boot Variable is unavailable

**Comment by oianson** [comment]
Hi @LukasMcClelland  sorry, forgot to say, I am using IOSXE :)

**Comment by jeaubin** [comment]
Can you please provide your Testbed file - Thanks

**Comment by oianson** [comment]
```
testbed:
  name: WLAN
  credentials:
      default:
          username: admin
          password: password
      enable:
          password: password

devices:

  D1-INETIU-C9800:
    connections:
      vty:
        ip: 10.52.127.211 
        port: 63701
        protocol: ssh
      defaults:
        via: vty
    os: iosxe
    platform: cat9k
    type: generic
    custom:
      abstraction:
        order: [os, platform]
```

**Comment by LukasMcClelland** [comment]
Hi @oianson, looks like [an api for verify_boot_variable](https://github.com/CiscoTestAutomation/genielibs/blob/79a213b68def18ef12fe60b0e1b2d748262bd493/pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/cat9k/platform/verify.py#L5)  was added in the last release. 

Please try updating pyats
```
pyats version update
```

**Comment by oianson** [comment]
Hi @LukasMcClelland 
I'm getting the same keyerror 'com' with this error

```
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobotApis.py", line 35, in run_keyword
    return self.api.get_api(name.strip().replace(' ', '_'), device_handler)(device_handler, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/genie/libs/sdk/apis/iosxe/cat9k/platform/verify.py", line 25, in verify_boot_variable
    next_boot_variables = device.api.get_boot_variables(
  File "src/genie/conf/base/api.py", line 101, in genie.conf.base.api.API.__getattr__.wrapper_match
  File "src/genie/conf/base/api.py", line 152, in genie.conf.base.api.API.get_api
```


```
pip list | grep pyats
pyats                          21.4
pyats.aereport                 21.4
pyats.aetest                   21.4
pyats.async                    21.4
pyats.connections              21.4
pyats.datastructures           21.4
pyats.easypy                   21.4
pyats.kleenex                  21.4
pyats.log                      21.4
pyats.reporter                 21.4
pyats.results                  21.4
pyats.robot                    21.3
pyats.tcl                      21.4
pyats.topology                 21.4
pyats.utils                    21.4
genie                          21.4
genie.libs.clean               21.4
genie.libs.conf                21.4
genie.libs.filetransferutils   21.4
genie.libs.health              21.4.2
genie.libs.ops                 21.4
genie.libs.parser              21.4
genie.libs.robot               21.3
genie.libs.sdk                 21.4.1
genie.telemetry                21.3
genie.trafficgen               21.3
```

**Comment by dwapstra** [comment]
How use pdb with robot https://wwwin-github.cisco.com/AS-Community/CXTA/blob/develop/src/CXTA/core/__init__.py#L12 

example:
```
from CXTA.core import bp

# breakpoint
bp()
```

Reference:

```
def bp():
    """
    Creates a break point with standard out.
    """
    import sys
    import pdb
    for attr in ('stdin', 'stdout', 'stderr'):
        setattr(sys, attr, getattr(sys, '__%s__' % attr))
    pdb.set_trace()
```

**Comment by oianson** [comment]
@dwapstra  hi :) 

I thought i was able to reproduce this in python too, but can't right now.. In Robot though, if i take this suite, run it using 'robot' command in a cxta container, it gives the 'com' error.  
If i take the same script, enter a python env which has robot and pyats/genie libs installed via pip, it works.  Any clue?

```
*** Settings ***
Library     pyats.robot.pyATSRobot
Library     genie.libs.robot.GenieRobot
Library     genie.libs.robot.GenieRobotApis

*** Test Cases ***

Test
    use genie testbed "testbed.yaml"
   connect to device "D1-INETIU-C9800"
   Verify Boot Variable   device=D1-INETIU-C9800   boot_images=packages.conf
```
