### ISSUE TITLE
IOSXE learn lisp exception

### ISSUE THREAD

**Issue by dpecak** [CiscoTestAutomation/genielibs#60]
I am trying to use LISP model in my testcases, but I cannot learn data properly.

Used to test
- Border device, Cat 9300, IOS-XE 17.5.1
- Edge device, Cat 9300, IOS-XE 17.5.1

```
(venv) # genie learn lisp --testbed-file ../sda.yaml

Learning '['lisp']' on devices '['Fab1-BC', 'Fab1-E']'
100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.27s/it]
+==============================================================================+
| Genie Learn Summary for device Fab1-BC                                       |
+==============================================================================+
|  Connected to Fab1-BC                                                        |
|  -   Log: ./connection_Fab1-BC.txt                                           |
|------------------------------------------------------------------------------|
|  Could not learn feature 'lisp'                                              |
|  -  Exception:      ./lisp_iosxe_Fab1-BC_exception.txt                       |
|  -  Ops structure:  ./lisp_iosxe_Fab1-BC_ops.txt                             |
|  -  Device Console: ./lisp_iosxe_Fab1-BC_console.txt                         |
|==============================================================================|


+==============================================================================+
| Genie Learn Summary for device Fab1-E                                        |
+==============================================================================+
|  Connected to Fab1-E                                                         |
|  -   Log: ./connection_Fab1-E.txt                                            |
|------------------------------------------------------------------------------|
|  Could not learn feature 'lisp'                                              |
|  -  Exception:      ./lisp_iosxe_Fab1-E_exception.txt                        |
|  -  Ops structure:  ./lisp_iosxe_Fab1-E_ops.txt                              |
|  -  Device Console: ./lisp_iosxe_Fab1-E_console.txt                          |
|==============================================================================|
```

Exception content - Border
```
(venv) # cat ./lisp_iosxe_Fab1-BC_exception.txt
Issue while building the feature

Traceback (most recent call last):
  File "src/genie/ops/base/maker.py", line 816, in genie.ops.base.maker.Leaf.make
  File "src/genie/ops/base/maker.py", line 58, in genie.ops.base.maker._merge_dict
  File "src/genie/ops/base/maker.py", line 58, in genie.ops.base.maker._merge_dict
  File "src/genie/ops/base/maker.py", line 58, in genie.ops.base.maker._merge_dict
  [Previous line repeated 3 more times]
  File "src/genie/ops/base/maker.py", line 64, in genie.ops.base.maker._merge_dict
Exception: number_registered_sites cannot be merged as it already exists with type <class 'int'>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/genie/ops/base/maker.py", line 352, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 819, in genie.ops.base.maker.Leaf.make
ValueError: Cannot set info to the object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/root/devnet/pyATS/genielibs/pkgs/ops-pkg/src/genie/libs/ops/lisp/iosxe/lisp.py", line 69, in learn
    self.make() ; self.make()
  File "/root/devnet/pyATS_GENIE_NetDevOpsLive/venv/lib64/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 359, in genie.ops.base.maker.Maker.make
Exception: Creation of the leaf with 'src' ['lisp_router_instances', '(?P<lisp_router_instance>.*)', 'service', 'ipv4', 'instance_id', '(?P<iid>.*)', 'map_server', 'summary', 'number_registered_sites'] failed to be created.
```

Exception content - Edge
```
(venv) # cat ./lisp_iosxe_Fab1-E_exception.txt
Issue while parsing: <class 'genie.libs.parser.iosxe.show_lisp.ShowLispService'>

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/root/devnet/pyATS/genielibs/pkgs/ops-pkg/src/genie/libs/ops/lisp/iosxe/lisp.py", line 69, in learn
    self.make() ; self.make()
  File "/root/devnet/pyATS_GENIE_NetDevOpsLive/venv/lib64/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Show Command: show lisp all service ipv4
Missing keys: [['lisp_router_instances', 0, 'service', 'ipv4', 'source_locator_configuration', 'vlans']]
```

Library versions
```
(venv) # pyats version check
You are currently running pyATS version: 21.5.1
Python: 3.6.8 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        21.5.1
  genie.libs.clean             21.5
  genie.libs.conf              21.5
  genie.libs.filetransferutils 21.5
  genie.libs.health            21.5
  genie.libs.ops               21.5
  genie.libs.parser            21.5
  genie.libs.robot             21.5
  genie.libs.sdk               21.5
  genie.telemetry              21.5
  genie.trafficgen             21.5
  pyats                        21.5.1
  pyats.aereport               21.5.1
  pyats.aetest                 21.5.1
  pyats.async                  21.5.1
  pyats.connections            21.5.1
  pyats.contrib                21.5
  pyats.datastructures         21.5.1
  pyats.easypy                 21.5.1
  pyats.kleenex                21.5.1
  pyats.log                    21.5.1
  pyats.reporter               21.5.1
  pyats.results                21.5.1
  pyats.robot                  21.5.1
  pyats.tcl                    21.5.1
  pyats.topology               21.5.1
  pyats.utils                  21.5.2
  unicon                       21.5.1
  unicon.plugins               21.5
```

**Comment by ThomasJRyan** [comment]
Thank you for providing as much information as you have. This looks like a few errors. One of which looks like the associated parsers might not be parsing correctly. Another looks like there are similar, conflicting keys in the ops.

As pyATS and Genie are open source projects, we like to encourage developers to contribute to the project. If you would like to attempt to solve this on your own and push the fix back to the repositories that would be greatly appreciated. If not you can send a log file of your failing run here pyats-support-ext@cisco.com (mention my name), and I can take a look into it. However, I can't guarantee a timeline for it
