### ISSUE TITLE
NXOS genie learn STP - LookupError: Could not find the OPS under nxos

### ISSUE THREAD

**Issue by aroramanish2009** [CiscoTestAutomation/genielibs#67]
Error:
```
2021-08-08T23:22:04: %AETEST-ERROR: Caught an exception while executing section setup:
2021-08-08T23:22:04: %AETEST-ERROR: Traceback (most recent call last):
2021-08-08T23:22:04: %AETEST-ERROR:   File "/root/netcheck/layer2check/layer2check.py", line 75, in setup
2021-08-08T23:22:04: %AETEST-ERROR:     self.stp_info = device.learn('stp')
2021-08-08T23:22:04: %AETEST-ERROR:   File "src/genie/conf/base/device.py", line 592, in genie.conf.base.device.Device.learn
2021-08-08T23:22:04: %AETEST-ERROR:   File "src/genie/ops/utils.py", line 51, in genie.ops.utils.get_ops
2021-08-08T23:22:04: %AETEST-ERROR: LookupError: Could not find the OPS under nxos
```

Version:
```
(pyats) root@ubuntu-2020:~/netcheck/layer2check# pyats version check
You are currently running pyATS version: 21.7
Python: 3.8.10 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        21.7
  genie.libs.clean             21.7
  genie.libs.conf              21.7
  genie.libs.filetransferutils 21.7
  genie.libs.health            21.7
  genie.libs.ops               21.7
  genie.libs.parser            21.7
  genie.libs.robot             21.7
  genie.libs.sdk               21.7
  genie.telemetry              21.7
  genie.trafficgen             21.7.1
  pyats                        21.7
  pyats.aereport               21.7
  pyats.aetest                 21.7
  pyats.async                  21.7
  pyats.connections            21.7
  pyats.contrib                21.7
  pyats.datastructures         21.7
  pyats.easypy                 21.7
  pyats.kleenex                21.7
  pyats.log                    21.7
  pyats.reporter               21.7
  pyats.results                21.7
  pyats.robot                  21.7
  pyats.tcl                    21.7
  pyats.topology               21.7
  pyats.utils                  21.7
  unicon                       21.7
  unicon.plugins               21.7
```

**Comment by aroramanish2009** [comment]
Hi @ThomasJRyan 
Please let me know if you need more outputs for the error as well as if I can help. 
Manish

**Comment by ThomasJRyan** [comment]
Hello,

Unfortunately, learning STP for NXOS has not yet been implemented https://github.com/CiscoTestAutomation/genielibs/tree/master/pkgs/ops-pkg/src/genie/libs//ops/stp

I can't currently give a timeline on when that will be implemented. Given the open-sourced nature of pyATS and Genie, we do like to encourage our users to develop and add such features if you are willing to do so

**Comment by aroramanish2009** [comment]
Hi Thomas 
Is there any quick Howto contribute guide for first time contributors ? Basically looking for directory layout, common links to other Libs etc so I spend less time reverse engineering the code. 
Anything that can help someone who is not familiar with the code layout. 
Thanks
Manish

**Comment by ThomasJRyan** [comment]
You can find how to create an ops here https://pubhub.devnetcloud.com/media/genie-docs/docs/userguide/Ops/developer/index.html
