### ISSUE TITLE
IOSXR learn OSPF key error

### ISSUE THREAD

**Issue by pwoconnor** [CiscoTestAutomation/genielibs#7]
I have run this test several times on different IOSXR devices running 6.2.3 and receive the same error. 

Genie output
```
Learning '['ospf']' on devices '['LAB-9010']'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.53s/it]
+==============================================================================+
| Genie Learn Summary for device LAB-9010                                      |
+==============================================================================+
|  Connected to LAB-9010                                                       |
|  -   Log: tests/normal_ospf/connection_LAB-9010.txt                          |
|------------------------------------------------------------------------------|
|  Could not learn feature 'ospf'                                              |
|  -  Exception:      tests/normal_ospf/ospf_iosxr_LAB-9010_exception.txt      |
|  -  Ops structure:  tests/normal_ospf/ospf_iosxr_LAB-9010_ops.txt            |
|  -  Device Console: tests/normal_ospf/ospf_iosxr_LAB-9010_console.txt        |
|==============================================================================|
```
Log text file

```Issue while parsing: <class 'genie.libs.parser.iosxr.show_ospf.ShowOspfVrfAllInclusive'>

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 310, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/home/patrick.oconnor/genie/env/lib/python3.6/site-packages/genie/libs/ops/ospf/iosxr/ospf.py", line 960, in learn
    self.make(final_call=True)
  File "src/genie/ops/base/base.py", line 95, in genie.ops.base.base.Base.make
  File "src/genie/ops/base/maker.py", line 272, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 375, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 302, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 392, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['vrf', 'default', 'address_family', 'ipv4', 'instance', '1', 'stub_router', 'on_startup', 'summary_lsa_metric'], ['vrf', 'default', 'address_family', 'ipv4', 'instance', '1', 'stub_router', 'on_startup', 'include_stub'], ['vrf', 'default', 'address_family', 'ipv4', 'instance', '1', 'stub_router', 'on_startup', 'external_lsa_metric'], ['vrf', 'default', 'address_family', 'ipv4', 'instance', '1', 'stub_router', 'on_startup', 'external_lsa'], ['vrf', 'default', 'address_family', 'ipv4', 'instance', '1', 'stub_router', 'on_startup', 'summary_lsa']]```

I can forward a copy of the output received from "show ospf vrf all inclusive" if needed

**Comment by jeaubin** [comment]
Can you please forward us the output to pyats-support-ext@cisco.com   and we will look into it;

**Comment by pwoconnor** [comment]
I have sent the output and included a link to this conversion for tracking.

**Comment by siming85** [comment]
will look into this on monday when the team is in office

**Comment by pwoconnor** [comment]
Hey guys, I'm just checking in to see if you might need anything else from my side on this issue?

**Comment by jeaubin** [comment]
Good timing! we just released the fix!

![image](https://user-images.githubusercontent.com/576771/56690927-a29b3700-66ac-11e9-9a90-6ccb1167d16a.png)

Please update your library like this

pip install genie.libs.parser==19.0.4b2 --upgrade

Give it a run and let us know!

**Comment by pwoconnor** [comment]
Awesome, I have upgraded and run the command again. New error

```
Issue while building the feature

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 310, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/home/patrick.oconnor/genie/env/lib/python3.6/site-packages/genie/libs/ops/ospf/iosxr/ospf.py", line 960, in learn
    self.make(final_call=True)
  File "src/genie/ops/base/base.py", line 95, in genie.ops.base.base.Base.make
  File "src/genie/ops/base/maker.py", line 272, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 375, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/patrick.oconnor/genie/env/lib/python3.6/site-packages/genie/libs/parser/iosxr/show_protocol.py", line 288, in cli
    if prot not in ospf_dict['redistribution']:
KeyError: 'redistribution' ```

**Comment by jeaubin** [comment]
Oh,    thats too bad! can you send us the output again ?

Thanks,

**Comment by pwoconnor** [comment]
You should have them shortly, thanks!

**Comment by karmoham** [comment]
Hi Patrick,

We have just released a beta package genie.libs.parser v 19.0.4b4 that contains the fix (Official release next Tuesday).

pip install genie.libs.parser --upgrade --pre

Please try it and let us know so we can move forward and close the ticket.

Thanks,
Karim

**Comment by pwoconnor** [comment]
Awesome, I just ran a test and all is working as intended now. Thanks!!!
