### ISSUE TITLE
Genie Learn ops routing model IOSXR local variable 'index' referenced before assignment

### ISSUE THREAD

**Issue by pwoconnor** [CiscoTestAutomation/genielibs#9]
As the title describes, receive unboundLocalError when running genie learn routing on IOSXR device. 

```
Issue while building the feature

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 310, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/home/patrick.oconnor/genie/env/lib/python3.6/site-packages/genie/libs/ops/routing/iosxr/routing.py", line 96, in learn
    self.make(final_call=True)
  File "src/genie/ops/base/base.py", line 95, in genie.ops.base.base.Base.make
  File "src/genie/ops/base/maker.py", line 272, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 375, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/patrick.oconnor/genie/env/lib/python3.6/site-packages/genie/libs/parser/iosxr/show_routing.py", line 534, in cli
    if index not in result_dict['vrf'][vrf]['address_family'][af]['routes'][route]['next_hop'] \
UnboundLocalError: local variable 'index' referenced before assignment
```
Files will be sent to pyats-support-ext@cisco.com

**Comment by jeaubin** [comment]
Thanks,   we are on it

**Comment by karmoham** [comment]
Hi Patrick,

We have just released a beta package genie.libs.parser v 19.0.4b4 that contains the fix (Official release next Tuesday).

pip install genie.libs.parser --upgrade --pre

Please try it and let us know so we can move forward and close the ticket.

Thanks,
Karim

**Comment by pwoconnor** [comment]
Awesome, I just ran a test and all is working as intended now. Thanks!!!
